#!/bin/bash
set -eu
KIT=squid

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-${KIT}
safe rm -rf secret/ci/baseline/${KIT}

header "Deploying BASELINE environment to verify functionality..."
cd dev
# make sure hooks are executable before screaming at shipit for failing.
genesis compile-kit --name $KIT -v 9.9.9 --force
cd ..
genesis add-secrets ci-baseline
genesis deploy -y ci-baseline
$BOSH -d ci-baseline-${KIT} instances --ps

header "Validating BASELINE environment..."
IP=$($BOSH -d ci-baseline-${KIT} vms --json | jq -r '.Tables[0].Rows[0].ips')
(export http_proxy=http://$IP:3128
 export https_proxy=http://$IP:3128
 curl -I https://google.com)

cleanup ci-baseline-${KIT}
