#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-squid
safe rm -rf secret/genesis-ci/squid
safe cp -rf secret/genesis-ci/static/squid secret/genesis-ci/squid/ci/baseline
safe cp -rf secret/genesis-ci/static/squid secret/genesis-ci/squid/ci/proto

header "Deploying BASELINE environment to verify functionality..."
genesis secrets --vault da-vault add ci-baseline
genesis deploy -n ci-baseline
$BOSH -d ci-baseline-squid instances --ps
header "Validating BASELINE squid proxy..."
IP=$($BOSH -d ci-baseline-squid vms --json | jq -r '.Tables[0].Rows[0].ips')
(export http_proxy=http://$IP:3128
 export https_proxy=http://$IP:3128
 curl -I https://google.com)
cleanup ci-baseline-squid
